// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app1.userdemo.v1.proto

package app1_userDemo_v1

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71d5b89ef1600e76, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	IsLogin              bool     `protobuf:"varint,1,opt,name=isLogin,proto3" json:"isLogin,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71d5b89ef1600e76, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetIsLogin() bool {
	if m != nil {
		return m.IsLogin
	}
	return false
}

type RegisteredRequest struct {
	Age                  uint64   `protobuf:"varint,1,opt,name=Age,proto3" json:"Age,omitempty"`
	Username             string   `protobuf:"bytes,2,opt,name=Username,proto3" json:"Username,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisteredRequest) Reset()         { *m = RegisteredRequest{} }
func (m *RegisteredRequest) String() string { return proto.CompactTextString(m) }
func (*RegisteredRequest) ProtoMessage()    {}
func (*RegisteredRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_71d5b89ef1600e76, []int{2}
}

func (m *RegisteredRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteredRequest.Unmarshal(m, b)
}
func (m *RegisteredRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteredRequest.Marshal(b, m, deterministic)
}
func (m *RegisteredRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredRequest.Merge(m, src)
}
func (m *RegisteredRequest) XXX_Size() int {
	return xxx_messageInfo_RegisteredRequest.Size(m)
}
func (m *RegisteredRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredRequest proto.InternalMessageInfo

func (m *RegisteredRequest) GetAge() uint64 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *RegisteredRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *RegisteredRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type RegisteredResponse struct {
	IsRegistered         bool     `protobuf:"varint,1,opt,name=isRegistered,proto3" json:"isRegistered,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RegisteredResponse) Reset()         { *m = RegisteredResponse{} }
func (m *RegisteredResponse) String() string { return proto.CompactTextString(m) }
func (*RegisteredResponse) ProtoMessage()    {}
func (*RegisteredResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_71d5b89ef1600e76, []int{3}
}

func (m *RegisteredResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RegisteredResponse.Unmarshal(m, b)
}
func (m *RegisteredResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RegisteredResponse.Marshal(b, m, deterministic)
}
func (m *RegisteredResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RegisteredResponse.Merge(m, src)
}
func (m *RegisteredResponse) XXX_Size() int {
	return xxx_messageInfo_RegisteredResponse.Size(m)
}
func (m *RegisteredResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RegisteredResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RegisteredResponse proto.InternalMessageInfo

func (m *RegisteredResponse) GetIsRegistered() bool {
	if m != nil {
		return m.IsRegistered
	}
	return false
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "app1.userDemo.v1.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "app1.userDemo.v1.LoginResponse")
	proto.RegisterType((*RegisteredRequest)(nil), "app1.userDemo.v1.RegisteredRequest")
	proto.RegisterType((*RegisteredResponse)(nil), "app1.userDemo.v1.RegisteredResponse")
}

func init() {
	proto.RegisterFile("app1.userdemo.v1.proto", fileDescriptor_71d5b89ef1600e76)
}

var fileDescriptor_71d5b89ef1600e76 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0x2c, 0x28, 0x30,
	0xd4, 0x2b, 0x2d, 0x4e, 0x2d, 0x4a, 0x49, 0xcd, 0xcd, 0xd7, 0x2b, 0x33, 0xd4, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0x12, 0x80, 0x8b, 0xbb, 0x40, 0xc4, 0x95, 0xdc, 0xb8, 0x78, 0x7c, 0xf2, 0xd3,
	0x33, 0xf3, 0x82, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0xa4, 0xb8, 0x38, 0x42, 0x8b, 0x53,
	0x8b, 0xf2, 0x12, 0x73, 0x53, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38, 0x83, 0xe0, 0x7c, 0x90, 0x5c,
	0x40, 0x62, 0x71, 0x71, 0x79, 0x7e, 0x51, 0x8a, 0x04, 0x13, 0x44, 0x0e, 0xc6, 0x57, 0xd2, 0xe4,
	0xe2, 0x85, 0x9a, 0x53, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc1, 0xc5, 0x9e, 0x59, 0x0c,
	0x16, 0x02, 0x9b, 0xc3, 0x11, 0x04, 0xe3, 0x2a, 0xc5, 0x72, 0x09, 0x06, 0xa5, 0xa6, 0x67, 0x16,
	0x97, 0xa4, 0x16, 0xa5, 0xa6, 0xc0, 0xec, 0x15, 0xe0, 0x62, 0x76, 0x4c, 0x87, 0x58, 0xc9, 0x12,
	0x04, 0x62, 0xa2, 0xb8, 0x84, 0x09, 0x8f, 0x4b, 0x98, 0xd1, 0x5c, 0x62, 0xc1, 0x25, 0x84, 0x6c,
	0x3c, 0xd4, 0x39, 0x4a, 0x5c, 0x3c, 0x99, 0xc5, 0x08, 0x71, 0xa8, 0x9b, 0x50, 0xc4, 0x8c, 0xd6,
	0x32, 0x42, 0xac, 0x04, 0x85, 0x8d, 0x90, 0x07, 0x17, 0x2b, 0xd8, 0xb9, 0x42, 0x72, 0x7a, 0xe8,
	0x81, 0xa6, 0x87, 0x1c, 0x62, 0x52, 0xf2, 0x38, 0xe5, 0xa1, 0x56, 0x87, 0x73, 0x71, 0x21, 0x2c,
	0x11, 0x52, 0xc6, 0x54, 0x8e, 0x11, 0x1a, 0x52, 0x2a, 0xf8, 0x15, 0x41, 0x0c, 0x4e, 0x62, 0x03,
	0x47, 0xaa, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x98, 0x30, 0xaa, 0x54, 0xee, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// UserDemoClient is the client API for UserDemo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserDemoClient interface {
	Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error)
	Registered(ctx context.Context, in *RegisteredRequest, opts ...grpc.CallOption) (*RegisteredResponse, error)
}

type userDemoClient struct {
	cc grpc.ClientConnInterface
}

func NewUserDemoClient(cc grpc.ClientConnInterface) UserDemoClient {
	return &userDemoClient{cc}
}

func (c *userDemoClient) Login(ctx context.Context, in *LoginRequest, opts ...grpc.CallOption) (*LoginResponse, error) {
	out := new(LoginResponse)
	err := c.cc.Invoke(ctx, "/app1.userDemo.v1.UserDemo/Login", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userDemoClient) Registered(ctx context.Context, in *RegisteredRequest, opts ...grpc.CallOption) (*RegisteredResponse, error) {
	out := new(RegisteredResponse)
	err := c.cc.Invoke(ctx, "/app1.userDemo.v1.UserDemo/Registered", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserDemoServer is the server API for UserDemo service.
type UserDemoServer interface {
	Login(context.Context, *LoginRequest) (*LoginResponse, error)
	Registered(context.Context, *RegisteredRequest) (*RegisteredResponse, error)
}

// UnimplementedUserDemoServer can be embedded to have forward compatible implementations.
type UnimplementedUserDemoServer struct {
}

func (*UnimplementedUserDemoServer) Login(ctx context.Context, req *LoginRequest) (*LoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (*UnimplementedUserDemoServer) Registered(ctx context.Context, req *RegisteredRequest) (*RegisteredResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Registered not implemented")
}

func RegisterUserDemoServer(s *grpc.Server, srv UserDemoServer) {
	s.RegisterService(&_UserDemo_serviceDesc, srv)
}

func _UserDemo_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDemoServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app1.userDemo.v1.UserDemo/Login",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDemoServer).Login(ctx, req.(*LoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserDemo_Registered_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisteredRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserDemoServer).Registered(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/app1.userDemo.v1.UserDemo/Registered",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserDemoServer).Registered(ctx, req.(*RegisteredRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserDemo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "app1.userDemo.v1.UserDemo",
	HandlerType: (*UserDemoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Login",
			Handler:    _UserDemo_Login_Handler,
		},
		{
			MethodName: "Registered",
			Handler:    _UserDemo_Registered_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app1.userdemo.v1.proto",
}
